name: Deploy EC2 Instance with CloudFormation
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy EC2 instance
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          template: ./ec2.yaml  # Path to your CloudFormation template
          name: MyGHAEC2InstanceStack # Give your stack a name
          # capabilities: CAPABILITY_IAM # Needed if your template creates IAM resources
          parameter-overrides: >-
            KeyName=Kennethians-kp-ohio # Replace with your EC2 Key Pair Name
